### ISSUE TITLE
Lists should share tails

### ISSUE THREAD

**Issue by masak** [jeremyschlatter/chime#6]
Using the Windows executable of the 0.4.0 release:

```
> (set L1 '(4 5 6))
(4 5 6)

> (set L2 (append '(1 2 3) L1))
(1 2 3 4 5 6)

> (set (2 L1) nil)
nil

> L1
(4 nil 6)

> L2
(1 2 3 4 5 6)
```

Expected `L2` to contain `(1 2 3 4 nil 6)`.

Same problem manifests with strings:

```
> (set s "foo")
"foo"

> (set s2 (append "bar" s))
"barfoo"

> (set (2 s) \O)
\O

> s
"fOo"

> s2
"barfoo"
```

Expected `"barfOo"`.

## Why?

Because `append` makes new pairs for everything except the list in the last argument:

```scheme
(def append args
  (if (no (cdr args)) (car args)
      (no (car args)) (apply append (cdr args))
                      (cons (car (car args))
                            (apply append (cdr (car args))
                                          (cdr args)))))
```

Specifically, the `(car args)` in the first condition means the last list is re-used.

**Comment by jeremyschlatter** [comment]
Fixed. Thanks!

I'm curious: how did you catch this?

**Comment by masak** [comment]
> I'm curious: how did you catch this?

The answer is some linear combination of "unhealthy amounts of re-readings of the Bel documents" and "trying to think deeply about optimization of Bel code", the latter especially from a [separation logic](https://cacm.acm.org/magazines/2019/2/234356-separation-logic/fulltext) point-of-view, reasoning about "this pair is freshly created and so can't be shared", etc.

The part about `append2` practically spells it out:

```
The next function, append, joins lists together:

> (append '(a b c) '(d e f))
(a b c d e f)
> (append '(a) nil '(b c) '(d e f))
(a b c d e f)

Its definition will be easier to understand if we look first at a 
two-argument version.

(def append2 (xs ys)
  (if (no xs)
      ys
      (cons (car xs) (append2 (cdr xs) ys))))

In English, if xs is empty, then just return ys. Otherwise return the
result of consing the first element of xs onto append of the rest of 
xs and ys. I.e. 

(append2 '(a b c) '(d e f))

becomes

(cons 'a (append2 '(b c) '(d e f)))
```

I also have [some half-baked/unimplemented ideas](https://github.com/masak/bel/blob/317ecd17fc39953c139278d5b312d9b5c886ea97/bytecode-format#L299) about a fast bytecode format and low-level imperative language, and when translating `append`, it was quite clear that a reference was being copied, not the list contents.

**Comment by masak** [comment]
Oh, and note how neither `snoc` nor `list` are affected by this &mdash; even though they directly call `append`, they do it in such a way that fresh pairs are always returned.

* The `args` vararg always consists entirely of fresh pairs. (Ultimately because of how `evcall2` is specified.) So `snoc` taking `(cdr args)` is guaranteed a fresh list.
* `list` passes in `nil`, which is not subject to freshness/aliasing.
