### ISSUE TITLE
The `chars` list doesn't contain `¦`

### ISSUE THREAD

**Issue by masak** [jeremyschlatter/chime#7]
Using the Windows executable of the 0.4.0 release:

```
> (get \A chars)
"A01000001"

> (get \¦ chars)
nil
```

According to the spec: "Bel doesn't specify which characters are in chars, but obviously they should include at least those in the Bel source."

**Comment by jeremyschlatter** [comment]
Good catch. Thanks!

**Comment by masak** [comment]
I'm sorry, my Haskell comprehension is slow &mdash; forgive me for asking straight-out:

```diff
diff --git a/src/Eval.hs b/src/Eval.hs
index 2348a1d..4e5d620 100644
--- a/src/Eval.hs
+++ b/src/Eval.hs
@@ -42,7 +42,7 @@ builtins = use nativeHook >>= \hook -> (globe <~) $ traverse
   , ("chars",
       let convert = flip B.foldl [] \acc -> (acc <>) . \w ->
               toObject . bool '0' '1' . testBit w <$> P.reverse [0..7]
-      in listToObject $ flip map [0..127] \i ->
+      in listToObject $ flip map ([0..127] <> [166]) \i ->
            chr i .* (
             listToObject $ convert $ encodeUtf8 $ singleton $ chr i :: EvalMonad (Object IORef)
           )
```

Does this fix also guarantee that `(charn \¦)` (correctly) gives `166`? A likely reading makes me think it will give `128`.

**Comment by jeremyschlatter** [comment]
You're right about the behavior this causes:

```
> (charn \¦)
128
```

In particular, this change does _not_ add unicode code points 128-165 to `chars`.

It's not clear to me that this is incorrect behavior, though. Can you say more about why you expect `(charn \¦)` to be `166`? By my read, the Bel spec is agnostic about this.

(Also, in case you'd like to play with this version of the code before I cut a new binary release, [bel-repl.com](https://bel-repl.com/) is now up-to-date with this commit.)

**Comment by masak** [comment]
> It's not clear to me that this is incorrect behavior, though. Can you say more about why you expect `(charn \¦)` to be `166`? By my read, the Bel spec is agnostic about this.

I think you're right about the Bel spec being agnostic about it. That had honestly not occurred to me.

My expectations are for `charn` to work like [`ord` in Perl](https://perldoc.perl.org/functions/ord.html) and for `nchar` to work like [`chr`](https://perldoc.perl.org/functions/chr.html). Furthermore, I expect there to be some mapping (even if it's not always trivial) between the index (`166`) and the bit representation (`11000010 10100110` in UTF-8; needed to check that one really carefully).

I agree that this is not explicit in the spec, and that technically _any_ mapping counts as an encoding. 166 just happens to be the value ("codepoint") that `¦` maps to under Unicode (and Latin-1).

All in all, I'm slightly less worried about `(charn \¦)` being `128` or any other value &mdash; the Bel spec is quite clear that matters of encodings are up to the implementations, and so scripts should already be written portably to take that into account.

> (Also, in case you'd like to play with this version of the code before I cut a new binary release, [bel-repl.com](https://bel-repl.com/) is now up-to-date with this commit.)

I've forgotten to say how cool it is that you have that site up. Kudos!

Confirmed &mdash; I get `128` on bel-repl.com. Going forward, I'll make bug reports based off of the version running in bel-repl.com, just to make sure I'm running against the latest version.
